/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthLayoutImport } from './routes/_auth/_layout'
import { Route as AppLayoutImport } from './routes/_app/_layout'
import { Route as AuthLayoutSignupImport } from './routes/_auth/_layout/signup'
import { Route as AuthLayoutSigninImport } from './routes/_auth/_layout/signin'

// Create Virtual Routes

const AppLayoutIndexLazyImport = createFileRoute('/_app/_layout/')()
const AppLayoutAboutLazyImport = createFileRoute('/_app/_layout/about')()

// Create/Update Routes

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutRoute = AppLayoutImport.update({
  id: '/_app/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutIndexLazyRoute = AppLayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any).lazy(() =>
  import('./routes/_app/_layout/index.lazy').then((d) => d.Route),
)

const AppLayoutAboutLazyRoute = AppLayoutAboutLazyImport.update({
  path: '/about',
  getParentRoute: () => AppLayoutRoute,
} as any).lazy(() =>
  import('./routes/_app/_layout/about.lazy').then((d) => d.Route),
)

const AuthLayoutSignupRoute = AuthLayoutSignupImport.update({
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutSigninRoute = AuthLayoutSigninImport.update({
  path: '/signin',
  getParentRoute: () => AuthLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/_layout': {
      preLoaderRoute: typeof AppLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_layout': {
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_layout/signin': {
      preLoaderRoute: typeof AuthLayoutSigninImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/signup': {
      preLoaderRoute: typeof AuthLayoutSignupImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_app/_layout/about': {
      preLoaderRoute: typeof AppLayoutAboutLazyImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/_layout/': {
      preLoaderRoute: typeof AppLayoutIndexLazyImport
      parentRoute: typeof AppLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AppLayoutRoute.addChildren([
    AppLayoutAboutLazyRoute,
    AppLayoutIndexLazyRoute,
  ]),
  AuthLayoutRoute.addChildren([AuthLayoutSigninRoute, AuthLayoutSignupRoute]),
])

/* prettier-ignore-end */
