services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.volumes/postgres-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - ./.volumes/pgadmin-data:/var/lib/pgadmin
  

