export const ERR_UNAUTHORIZED = "UNAUTHORIZED";
export const ERR_TOKEN_EXPIRED = "TOKEN_EXPIRED";
export const HTTP_STATUS_UNAUTHORIZED = 401;

export const ERR_FORBIDDEN = "FORBIDDEN";
export const HTTP_STATUS_FORBIDDEN = 403;

export const ERR_NOT_FOUND = "NOT_FOUND";
export const HTTP_STATUS_NOT_FOUND = 404;

export const ERR_CONFLICT = "CONFLICT";
export const HTTP_STATUS_CONFLICT = 409;

export const ERR_BAD_REQUEST = "BAD_REQUEST";
export const HTTP_STATUS_BAD_REQUEST = 400;

export const ERR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500;

export type ERRSTATUS =
  | "UNAUTHORIZED"
  | "TOKEN_EXPIRED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "CONFLICT"
  | "BAD_REQUEST"
  | "INTERNAL_SERVER_ERROR";
